[plugin]
repository = "https://github.com/Dragonw233/GaugeOMatic.git"
commit = "10335848d3883c5f0a79b7f2505df2a7e678ce00"
owners = [
    "ItsBexy，Dragonw2333",
]
changelog = """
## WIDGETS
- Fixed an issue with scaling options for the `Shimmering Halo` widget
- Added Icon and Sound options to counter widgets
"""
