[plugin]
repository = "https://github.com/Dragonw233/GaugeOMatic.git"
commit = "860e4477e220cd169d127a10f1d2c82049892243"
owners = [
    "ItsBexy，Dragonw2333",
]
changelog = """
## WIDGETS
- Fixed an issue with scaling options for the `Shimmering Halo` widget
- Added Icon and Sound options to counter widgets
"""
